version: "3.6"

networks:
  gateway:
    external: true
    name: "gateway"

services:
  pihole:
    container_name: "pihole"
    environment:
      - "WEBPASSWORD=$WEBPASSWORD"
      - "TZ=Europe/London"
    hostname: "pihole"
    image: "pihole/pihole:latest"
    networks:
      - "gateway"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    restart: "unless-stopped"
    volumes:
      - "/data/compose/51/etc-dnsmasq.d:/etc/dnsmasq.d"
      - "/data/compose/51/etc-pihole:/etc/pihole"