version: "3.6"

networks:
  gateway:
    external: true
    name: "gateway"

services:
  cadvisor:
    container_name: "cadvisor"
    image: "gcr.io/cadvisor/cadvisor:0.99-porterdavid"
    command:
    - "--enable_metrics=cpu,memory,network"
    - "--store_container_labels=false"
    - "--docker_only=true"
    - "--housekeeping_interval=30s"
    networks:
      - "gateway"
    restart: "unless-stopped"
    volumes:
      - "/var/run:/var/run:ro"
      - "/:/rootfs:ro"
      - "/sys:/sys:ro"
      - "/var/lib/docker:/var/lib/docker:ro"